export const Enlanguage = {
  'logon':'Login',
  'logon.welcome':'Welcome to the',
  'logon.field_mgr_system':'RAN EMS & Non-RT RIC Portal',
  'logon.user_logon':'USER LOGIN',
  'logon.password_error':'Username or password Eentered Incorrectly',
  'logon.required_error':'Please Enter Account or Password',
  'logon.401':'Session ID has expired, please log in again',
  'logon.403':'Username or password Eentered Incorrectly',
  'logon.404':'This account does not exist',
  'index.menu_dashboard':'Dashboard',
  'index.menu_fieldMgr':'Field Management',
  'index.menu_iRmSys':'RAN EMS & Non-RT RIC Portal',
  'index.menu_gNB':'gNB Management',
  'index.menu_componentMgr':'Component Management',
  'index.menu_faultMgr':'Fault Management',
  'index.menu_performMgr':'Performance Management',
  'index.menu_softwareMgr':'Software Management',
  'index.menu_scheduleMgr':'Schedule Management',
  'index.menu_logMgr':'Log Management',
  'index.menu_accountMgr':'Account Management',
  'index.netFun':'Network Functions',
  'index.faultMsg':'Fault Messages',
  'index.viewMore':'View More',
  'index.view':'View',
  'index.resourceMsg':'Resource Information',
  'index.cpuLoading':'CPU Loading',
  'index.diskUsage':'Disk Usage',
  'index.memoryUsage':'Memory Usage',
  'index.networkThroughput':'Network Throughput',
  'table.header_name':'Name',
  'table.header_dmsCount':'DMS Counts',
  'table.header_nfCount':'NF Counts',
  'table.header_faultCount':'Fault Counts',
  'field.list':'Field List',
  'table.globalID':'Global ID',
  'table.Status':'Status',
  'table.performance':'Performance',
  'table.delete':'Delete',
  'information':'Information',
  'basic.info':'Basic Information',
  'nf.list':'NF List',
  'resource.pools':'Resource Pools',
  'ims.endpoint':'IMS Endpoint',
  'software.info':'Software Information',
  'version':'Version',
  'update':'Update',
  'theme':'Adjust theme',
  'logout_now':'Logout Now',
  'view_detail':'View this item in detail',
  'createNF':'Create a new NF',
  'delItem':'Delete this item',
  'updateSoftware':'Update this software',
  'nfRun':'NF running',
  'nfNotRun':'NF not running',
  'search':'Search',
  'stopDE':'Stop deploy',
  'startDE':'Start deploy',
  'createNFcapacity':'Create a new NF capacity',
  'a_search':'Advanced Search',
  'addSoftware':'Add New Software',
  'delsoftware':'Delete Software',
  'type':'Type',
  'description':'Description',
  'fileName':'File Name',
  'action':'Action',
  'time':'Time',
  'severity':'Severity',
  'NFmgr':'Network Function Management',
  'upload':'Upload',
  'softwareFile':'Software File',
  'faultContext':'Fault Context',
  'processComment':'Process Comment',
  'npInfo':'Network Performance Information',
  'send':'Send',
  'receive':'Receive',
  'confirm_del_soft':'Confirm to Delete Software',
  'confirm_del_field':'Confirm to Delete Field',
  'confirm_del_nf':'Confirm to Delete NF',
  'performance_Advanced_Search':'Advanced Search',
  'software_update':'Software Update',
  'add_field':'Create Field',
  'detail':'Detail',
  'limit.max':'max',
  'limit.min':'min',
  'modify_faultMsg_status':'Modify Fault Message Status',
  'confirm_modify':'Confirm to modify',
  'pending_error':'Pending Error',
  'resolved':'Resolved',
  'no_results':'No results were found. Please verify your search terms and try again.',
  'firm':'Firm',
  'model':'Model',
  'manufacturer':'Manufacturer',
  'notes':'Notes',
  'upload_time':'Upload Time',
  'file.Url':'File/Url',
  'ftp.account':'FTP Account',
  'ftp.password':'FTP Password',
  'upload.file':'Upload File',
  'url':'Url',
  'add.method':'Add Method',
  'file.size':'File Size'
}
