export const Enlanguage = {

  'logon':'Login',
  'logon.welcome':'Welcome to the',
  'logon.field_mgr_system':'Athena Orchestrator',
  'logon.user_logon':'USER LOGIN',
  'logon.password_error':'Username or password Eentered Incorrectly',
  'logon.required_error':'Please Enter Account or Password',
  'logon.401':'Session ID has expired, please log in again',
  'logon.403':'Username or password Eentered Incorrectly',

  'logon.404':'This account does not exist',
  'index.menu_dashboard':'Dashboard',
  'index.menu_fieldMgr':'Field Management',
  'index.menu_iRmSys':'Athena Orchestrator',
  'index.menu_gNB':'gNB Management',
  'index.menu_componentMgr':'Component Management',
  'index.menu_faultMgr':'Fault Management',
  'index.menu_performMgr':'Performance Management',
  'index.menu_softwareMgr':'Software Management',
  'index.menu_scheduleMgr':'Schedule Management',
  'index.menu_accountMgr':'Account Management',
  'index.menu_logMgr':'Log Management',

  'index.netFun':'Network Functions',
  'index.faultMsg':'Fault Messages',
  'index.viewMore':'View More',
  'index.view':'View',
  'index.resourceMsg':'Resource Information',
  'index.cpuLoading':'CPU Loading',
  'index.diskUsage':'Disk Usage',
  'index.memoryUsage':'Memory Usage',
  'index.networkThroughput':'Network Throughput',
  'table.header_name':'Name',
  'table.header_dmsCount':'DMS Counts',
  'table.header_nfCount':'NF Counts',
  'table.header_faultCount':'Fault Counts',
  'field.list':'Field List',
  'table.globalID':'Global ID',
  'table.Status':'Status',
  'table.performance':'Performance',
  'table.delete':'Delete',
  
  //Common Items
  'cancel':'Cancel',

  // Fault Management
  'fm.start':'StartTime',
  'fm.end':'EndTime',
  'fm.no':'No.',
  'fm.field':'Field Name',
  'fm.gnb':'gNB Name',
  'fm.component':'Component Name',
  'fm.alarm':'Alarm Name',
  'fm.severity':'Severity',
  'fm.count':'Count',
  'fm.occurtime':'OccurTime',
  'fm.createtime':'Create Time',
  'fm.updatetime':'Update Time',
  'fm.status':'Status',
  'fm.situation':'Situation',
  'fm.owner':'Acknowledge Owner',
  'fm.view':'View',
  'fm.total1':'Total',
  'fm.total2':'Alarms',
  'fm.eType':'Event Type',
  'fm.eCause':'Event Cause',
  'fm.eDesc':'Event Description',
  'fm.detail':'Fault Message Detail',
  'fm.addsitch':'Add Situation',
  'fm.sHistory':'Situation History',
  'fm.add':'Add',
  'fm.pending':'Pending',
  'fm.ended':'Ended',

  // Performance Management
  'pm.field':'Field Name',
  'pm.accessibility':'Accessibility',
  'pm.integrity':'Integrity (4 Indicator)',
  'pm.retainability':'Retainability',
  'pm.efficiency':'Energy Efficiency',
  'pm.utilization':'Utilization (5 Indicator)',
  'pm.mobility':'Mobility',
  'information':'Information',
  'basic.info':'Basic Information',
  'nf.list':'NF List',
  'resource.pools':'Resource Pools',
  'ims.endpoint':'IMS Endpoint',
  'software.info':'Software Information',
  'version':'Version',
  'update':'Update',
  'theme':'Adjust theme',
  'logout_now':'Logout Now',
  'view_detail':'View this item in detail',
  'createNF':'Create a new NF',
  'delItem':'Delete this item',
  'updateSoftware':'Update this software',
  'nfRun':'NF running',
  'nfNotRun':'NF not running',
  'search':'Search',
  'stopDE':'Stop deploy',
  'startDE':'Start deploy',
  'createNFcapacity':'Create a new NF capacity',
  'a_search':'Advanced Search',
  'addSoftware':'Add New Software',
  'delsoftware':'Delete Software',
  'type':'Type',
  'description':'Description',
  'fileName':'File Name',
  'action':'Action',
  'time':'Time',
  'severity':'Severity',
  'NFmgr':'Network Function Management',
  'upload':'Upload',
  'softwareFile':'Software File',
  'faultContext':'Fault Context',
  'processComment':'Process Comment',
  'npInfo':'Network Performance Information',
  'send':'Send',
  'receive':'Receive',
  'confirm_del_soft':'Confirm to Delete Software',
  'confirm_del_field':'Confirm to Delete Field',
  'confirm_del_nf':'Confirm to Delete NF',
  'performance_Advanced_Search':'Advanced Search',
  'software_update':'Software Update',
  'add_field':'Create Field',
  'detail':'Detail',
  'limit.max':'max',
  'limit.min':'min',
  'modify_faultMsg_status':'Modify Fault Message Status',
  'confirm_modify':'Confirm to modify',
  'pending_error':'Pending', //Modify by Charles (Pending Error->Pending)
  'resolved':'Resolved',
  'no_results':'No results were found. Please verify your search terms and try again.',

  //Dashboard
  'num_fields':'Number of Field',
  'num_gNBs':'Number of gNBs',
  'num_UEs':'Number of UEs',
  'coverage':'Coverage',
  'critical_Alarm':'Critical Alarm',
  'major_Alarm':'Major Alarm',
  'minor_Alarm':'Minor Alarm',
  'warning_Alarm':'Warning Alarm',
  'dashboard.view':'View',
  
  //Software Management
  'firm':'Firm',
  'model':'Model',
  'manufacturer':'Manufacturer',
  'notes':'Notes',
  'upload_time':'Upload Time',
  'file.Url':'File/Url',
  'ftp.account':'FTP Account',
  'ftp.password':'FTP Password',
  'upload.file':'Upload File',
  'url':'Url',
  'add.method':'Add Method',
  'file.size':'File Size',
  'field_list':'Field List',
  'software_version':'Software Version',
  'time.end':'～ ',
  
  // Component Management (元件管理)
  'cm.name':'Component Name',
  'cm.provision':'Provision',
  'ExportCSV':'Export Result.csv',
  'cm.add':'Add Component',
  'cm.type':'Component Type',
  'cm.ip':'Component IP',
  'cm.port':'Component Port',
  'cm.mac':'Component MAC',
  'cm.acc':'Component Account',
  'cm.passw':'Component Password',
  'cm.manufacturer':'Manufacturer',
  'cm.model':'Model',
  'cm.delete':'Delete Component',
  'cm.confirm_del':'Confirm to Delete Component',
  'cm.unable_del':'Can not delete the component which has been assigned to a certain gNB',
  'cm.error':'ERROR',

  // Account Management
  'user_account':'User',
  'key_account':'Password',
  'role_account':'Role',
  'expired_time_account':'Expired Time',
  'addaccount':'Create Account',
  'delaccount':'Delete Account',
  'confirm_del_acc':'Confirm to Delete Account',

  // Log Management @10/31 add by yuchen
  'LogLists': 'Log Lists',
  'UserLogs': 'User Logs',
  'NELogs': 'NE Logs',            // NE = Network Element
  'Log.start':'Execution Time',   // @11/17 changed by yuchen
  'Log.end':'～ ',                // @11/17 changed by yuchen
  'Log.total':'Total',            // @11/21 add by yuchen

  'UserLog.No':'No.',
  'UserLog.userid':'User',
  'UserLog.logtype':'Type',
  'UserLog.loglevel':'Level',
  'UserLog.logmsg':'Action Executed',
  'UserLog.logtime':'Execution Time',
  'UserLog.view':'View',
  'UserLog.single':'User Log',  // @11/21 add by yuchen
  'UserLog.total':'User Logs',  // @11/21 changed by yuchen
  'UserLog.logKeywordString':'Action Executed',  // @11/17 changed by yuchen
  'UserLog.detail':'User Log Detail', // @11/03 add by yuchen
  'UserLog.detailclose':'Close',      // @11/03 add by yuchen
  'UserLog.ExportCSV':'Export User Logs to .csv', // @11/07 add by yuchen


  'NElog.No':'No.',
  'NElog.userid':'User',
  'NElog.operation':'Type',
  'NElog.req_data':'Request Data',
  'NElog.resp_data':'Response Data',
  'NElog.logtime':'Execution Time',
  'NElog.view':'View',
  'NElog.single':'NE Log',   // @11/21 add by yuchen
  'NElog.total':'NE Logs',   // @11/21 changedby yuchen
  'NElog.logKeywordString':'Request / Response Data',  // @11/17 changed by yuchen
  'NElog.detail':'NE Log Detail',        // @11/03 add by yuchen
  'NElog.detailclose':'Close',           // @11/03 add by yuchen
  'NElog.ExportCSV':'Export NE Logs to .csv',   // @11/07 add by yuchen
}
