export const TwLanguage = {

  'logon':'登入',
  'logon.welcome':'歡迎',
  'logon.field_mgr_system':'Athena Orchestrator',
  'logon.user_logon':'用戶登入',
  'logon.password_error':'用戶名或密碼輸入錯誤',
  'logon.required_error':'請輸入帳號或密碼',
  'logon.401':'Session ID 已過期，請重新登錄',
  'logon.403':'用戶名或密碼輸入錯誤',
  'logon.404':'此帳號不存在',

  'index.menu_dashboard':'主畫面',
  'index.menu_fieldMgr':'場域管理',
  'index.menu_iRmSys':'Athena Orchestrator',
  'index.menu_gNB':'基站管理',
  'index.menu_componentMgr':'Component Management',
  'index.menu_faultMgr':'故障管理',
  'index.menu_performMgr':'效能管理',
  'index.menu_softwareMgr':'軟體管理',
  'index.menu_scheduleMgr':'排程管理',
  'index.menu_accountMgr':'帳號管理',
  'index.menu_logMgr':'日誌管理',   // "log" -> "日誌" @10/25 by yuchen

  'index.netFun':'網路功能',
  'index.faultMsg':'告警資訊',
  'index.viewMore':'詳情訊息',
  'index.view':'詳情訊息',
  'index.resourceMsg':'資源訊息',
  'index.cpuLoading':'CPU 負載',
  'index.diskUsage':'硬碟使用量',
  'index.memoryUsage':'內存使用量',
  'index.networkThroughput':'網路吞吐量',
  'table.header_name':'名稱',
  'table.header_dmsCount':'DMS 數量',
  'table.header_nfCount':'NF 數量',
  'table.header_faultCount':'故障數量',
  'field.list':'場域列表',
  'table.globalID':'Global ID',
  'table.Status':'部署情況',
  'table.performance':'部署狀態',
  'table.delete':'刪除',
  
  //Common Items (共用項目)
  'cancel':'取消',

  // Fault Management (故障管理)
  'fm.start':'起始時間',
  'fm.end':'結束時間',
  'fm.no':'編號',
  'fm.field':'場域名稱',
  'fm.gnb':'基站名稱',
  'fm.component':'元件名稱',
  'fm.alarm':'告警名稱',
  'fm.severity':'嚴重度',
  'fm.count':'發生次數',
  'fm.occurtime':'事件時間',
  'fm.createtime':'首次記錄時間',
  'fm.updatetime':'最新更新時間',
  'fm.status':'告警狀態',
  'fm.situation':'處理狀況',
  'fm.owner':'回應人員',
  'fm.view':'檢視',
  'fm.total1':'全部共有',
  'fm.total2':'項訊息',
  'fm.eType':'告警分類',
  'fm.eCause':'告警原因',
  'fm.eDesc':'詳細描述',
  'fm.detail':'詳細告警訊息',
  
  // Performance Management (效能管理)
  'pm.field':'場域名稱',
  'pm.accessibility':'可用性',
  'pm.integrity':'完整性 (4指標)',
  'pm.retainability':'穩定性',
  'pm.efficiency':'能源效率',
  'pm.utilization':'利用率 (5指標)',
  'pm.mobility':'移動性',
  'information':'詳情資訊',
  'basic.info':'基本訊息',
  'nf.list':'NF 列表',
  'resource.pools':'Resource Pools',
  'ims.endpoint':'IMS 末端端點',
  'software.info':'軟體訊息',
  'version':'版本',
  'update':'更新',
  'theme':'調整主題',
  'logout_now':'登出',
  'view_detail':'詳細查看此項目',
  'createNF':'新增 NF',
  'delItem':'刪除此項',
  'updateSoftware':'更新此軟件',
  'nfRun':'NF 執行中',
  'nfNotRun':'NF 停止執行',
  'search':'搜索',
  'stopDE':'停止部署',
  'startDE':'開始部署',
  'createNFcapacity':'新增 NF Capacity',
  'a_search':'進階搜索',
  'addSoftware':'新增軟體',
  'delsoftware':'刪除軟體',
  'type':'類型',
  'description':'描述',
  'fileName':'軟體名稱',
  'action':'動作',
  'time':'時間',
  'severity':'嚴重性',
  'NFmgr':'網路功能管理',
  'upload':'檔案上傳',
  'softwareFile':'軟體',
  'faultContext':'故障內容',
  'processComment':'備註',
  'npInfo':'網路效能訊息',
  'send':'傳送量',
  'receive':'接收量',
  'confirm_del_soft':'確定要刪除軟體',
  'confirm_del_field':'確定要刪除場域',
  'confirm_del_nf':'確定要刪除 NF',
  'performance_Advanced_Search':'進階查詢',
  'software_update':'軟體更新',
  'add_field':'場域新增',
  'detail':'NF動態',
  'limit.max':'上限',
  'limit.min':'下限',
  'modify_faultMsg_status':'修改故障訊息狀態',
  'confirm_modify':'確認修改',
  'pending_error':'待處理',
  'resolved':'已解決',
  'no_results':'未找到您想搜尋的相關數據。請嘗試修改搜尋關鍵字',
  'firm':'Firm',
  'model':'Model',
  'manufacturer':'Manufacturer',
  'notes':'備註',
  'upload_time':'上傳時間',
  'file.Url':'新增方式',
  'ftp.account':'FTP 帳號',
  'ftp.password':'FTP 密碼',
  'upload.file':'上傳檔案',
  'url':'連結',
  'add.method':'選擇新增方式',
  'file.size':'檔案大小',
  'field_list':'場域列表',
  
  // Account Management (帳號管理)
  'user_account':'帳號',
  'key_account':'密碼',
  'role_account':'角色',
  'expired_time_account':'有效時間',
  'addaccount':'帳號新增',
  'delaccount':'帳號刪除',
  'confirm_del_acc':'確定帳號刪除',

  // Log Management (日誌管理)  @10/31 add by yuchen
  'LogLists': '日誌列表',
  'UserLogs': '用戶日誌',
  'NELogs': '網元日誌',     // NE = Network Element
  'Log.start':'起始時間',   // @11/01 add by yuchen
  'Log.end':'結束時間',     // @11/01 add by yuchen

  'UserLog.No':'編號',
  'UserLog.userid':'用戶',
  'UserLog.logtype':'類型',
  'UserLog.loglevel':'層級',
  'UserLog.logmsg':'執行動作',
  'UserLog.logtime':'執行時間',
  'UserLog.view':'檢視',
  'UserLog.total1':'總共',       // @11/01 add by yuchen
  'UserLog.total2':'項用戶日誌訊息', // @11/01 add by yuchen
  'UserLog.detail':'詳細用戶日誌訊息', // @11/03 add by yuchen
  'UserLog.detailclose':'關閉',      // @11/03 add by yuchen
  
  'NElog.No':'編號',
  'NElog.userid':'用戶',
  'NElog.operation':'類型',
  'NElog.req_data':'請求數據',
  'NElog.resp_data':'回應數據',
  'NElog.logtime':'執行時間',
  'NElog.view':'檢視',
  'NElog.total1':'總共',            // @11/01 add by yuchen
  'NElog.total2':'項網元日誌訊息',     // @11/01 add by yuchen
  'NElog.logKeywordString':'關鍵字:', // @11/03 add by yuchen
  'NElog.detail':'詳細網元日誌訊息',    // @11/03 add by yuchen
  'NElog.detailclose':'關閉',         // @11/03 add by yuchen
}
