export const TwLanguage = {
  'logon':'登入',
  'logon.welcome':'歡迎',
  'logon.field_mgr_system':'Athena Orchestrator',
  'logon.user_logon':'用戶登入',
  'logon.password_error':'用戶名或密碼輸入錯誤',
  'logon.required_error':'請輸入帳號或密碼',
  'logon.401':'Session ID 已過期，請重新登錄',
  'logon.403':'用戶名或密碼輸入錯誤',
  'logon.404':'此賬號不存在',
  'index.menu_dashboard':'主畫面',
  'index.menu_fieldMgr':'Field 管理',
  'index.menu_iRmSys':'Athena Orchestrator',
  'index.menu_gNB':'gNB 管理',
  'index.menu_componentMgr':'Component Management',
  'index.menu_faultMgr':'故障管理',
  'index.menu_performMgr':'效能管理',
  'index.menu_softwareMgr':'軟體管理',
  'index.menu_scheduleMgr':'排程管理',
  'index.menu_logMgr':'Log管理',
  'index.menu_accountMgr':'帳號管理',
  'index.netFun':'網路功能',
  'index.faultMsg':'告警資訊',
  'index.viewMore':'詳情信息',
  'index.view':'詳情信息',
  'index.resourceMsg':'資源信息',
  'index.cpuLoading':'CPU 負載',
  'index.diskUsage':'硬碟使用量',
  'index.memoryUsage':'內存使用量',
  'index.networkThroughput':'網路流通量',
  'table.header_name':'名稱',
  'table.header_dmsCount':'DMS 數量',
  'table.header_nfCount':'NF 數量',
  'table.header_faultCount':'故障數量',
  'field.list':'Field 列表',
  'table.globalID':'Global ID',
  'table.Status':'部署情況',
  'table.performance':'部署狀態',
  'table.delete':'刪除',
  //Fault Management (故障管理)
  'fm.no':'序號',
  'fm.field':'場域名稱',
  'fm.gnb':'基站名稱',
  'fm.component':'元件名稱',
  'fm.alarm':'告警名稱',
  'fm.severity':'嚴重度',
  'fm.count':'發生次數',
  'fm.occurtime':'事件時間',
  'fm.status':'告警狀態',
  'fm.situation':'處理狀況',
  'fm.owner':'回應人員',
  //Performance Management (效能管理)
  'pm.field':'場域名稱',
  'pm.accessibility':'可用性',
  'pm.integrity':'完整性 (4指標)',
  'pm.retainability':'穩定性',
  'pm.efficiency':'能源效率',
  'pm.utilization':'利用率 (5指標)',
  'pm.mobility':'移動性',
  'information':'詳情資料',
  'basic.info':'基本信息',
  'nf.list':'NF 列表',
  'resource.pools':'Resource Pools',
  'ims.endpoint':'IMS 末端端點',
  'software.info':'軟體信息',
  'version':'版本',
  'update':'更新',
  'theme':'調整主題',
  'logout_now':'登出',
  'view_detail':'詳細查看此項目',
  'createNF':'新增 NF',
  'delItem':'刪除此項',
  'updateSoftware':'更新此軟件',
  'nfRun':'NF 執行中',
  'nfNotRun':'NF 停止執行',
  'search':'搜索',
  'stopDE':'停止部署',
  'startDE':'開始部署',
  'createNFcapacity':'新增 NF Capacity',
  'a_search':'進階搜索',
  'addSoftware':'新增軟體',
  'delsoftware':'刪除軟體',
  'type':'類別',
  'description':'描述',
  'fileName':'軟體名稱',
  'action':'動作',
  'time':'時間',
  'severity':'嚴重性',
  'NFmgr':'網路功能管理',
  'upload':'檔案上傳',
  'softwareFile':'軟體',
  'faultContext':'故障內容',
  'processComment':'備註',
  'npInfo':'網路效能信息',
  'send':'傳送量',
  'receive':'接收量',
  'confirm_del_soft':'確定要刪除軟體',
  'confirm_del_field':'確定要刪除 Field',
  'confirm_del_nf':'確定要刪除 NF',
  'performance_Advanced_Search':'進階查詢',
  'software_update':'軟體更新',
  'add_field':'新增 Field',
  'detail':'NF動態',
  'limit.max':'上限',
  'limit.min':'下限',
  'modify_faultMsg_status':'修改故障信息狀態',
  'confirm_modify':'確認修改',
  'pending_error':'待處理',
  'resolved':'已解決',
  'no_results':'没有找到与您的搜索相关的数据。请尝试修改搜索词',
  'firm':'Firm',
  'model':'Model',
  'manufacturer':'Manufacturer',
  'notes':'備註',
  'upload_time':'上傳時間',
  'file.Url':'新增方式',
  'ftp.account':'FTP 帳號',
  'ftp.password':'FTP 密碼',
  'upload.file':'上傳檔案',
  'url':'連結',
  'add.method':'選擇新增方式',
  'file.size':'檔案大小',
  'field_list':'場域列表'
}
